In [1]:
import os
import pandas as pd
from datetime import datetime, timedelta
import glob

In [2]:
hrs = sorted(list(range(24)) * 2)
mins = [0, 30] * 24

In [4]:
df = [pd.read_csv(file) for file in glob.glob('dataset/**/*.csv', recursive=True)]
df = pd.concat(df, ignore_index=True)
df['DATETIME'] = df['DATE'].apply(datetime.strptime, args=('%d %b %Y',)) + \
             df['PERIOD'].apply(lambda x: timedelta(hours=hrs[x-1], minutes=mins[x-1]))
df = df.sort_values('DATETIME').reset_index(drop=True)
df.to_feather('wep_2012_22.feather')

df

,INFORMATION TYPE,DATE,PERIOD,WEP ($/MWh),USEP ($/MWh),AFP ($/MWh),HEUC ($/MWh),MEUC ($/MWh),EMC Fees ($/MWh),PSO Fees ($/MWh),EMC Price Cap Fees ($/MWh),EMC Price Adj Fees ($/MWh),HEUR ($/MWh),HLCU ($/MWh),DATETIME
0,WEP,01 Jan 2012,1,188.58,185.09,1.61,1.08,0.18,0.38,0.2400,NaN,NaN,NaN,NaN,2012-01-01 00:00:00
1,WEP,01 Jan 2012,2,187.22,183.60,1.62,1.20,0.18,0.38,0.2400,NaN,NaN,NaN,NaN,2012-01-01 00:30:00
2,WEP,01 Jan 2012,3,177.84,176.49,0.70,-0.15,0.18,0.38,0.2400,NaN,NaN,NaN,NaN,2012-01-01 01:00:00
3,WEP,01 Jan 2012,4,178.44,176.50,1.65,-0.51,0.18,0.38,0.2400,NaN,NaN,NaN,NaN,2012-01-01 01:30:00
4,WEP,01 Jan 2012,5,177.12,176.43,0.66,-0.77,0.18,0.38,0.2400,NaN,NaN,NaN,NaN,2012-01-01 02:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187867,WEP,18 Sep 2022,44,249.79,245.80,0.23,NaN,3.40,NaN,0.3021,0.3589,0.0,-0.30,0.0,2022-09-18 21:30:00
187868,WEP,18 Sep 2022,45,180.19,176.94,0.23,NaN,3.40,NaN,0.3021,0.3589,0.0,-1.04,0.0,2022-09-18 22:00:00
187869,WEP,18 Sep 2022,46,181.51,176.82,0.22,NaN,3.40,NaN,0.3021,0.3589,0.0,0.41,0.0,2022-09-18 22:30:00
187870,WEP,18 Sep 2022,47,161.96,157.47,0.19,NaN,3.40,NaN,0.3021,0.3589,0.0,0.24,0.0,2022-09-18 23:00:00
187871,WEP,18 Sep 2022,48,129.18,124.45,0.18,NaN,3.40,NaN,0.3021,0.3589,0.0,0.49,0.0,2022-09-18 23:30:00